ARG OPENJDK_TAG=21
FROM openjdk:${OPENJDK_TAG}
ARG VERSION
ARG BUILD
RUN mkdir /jar
COPY ./start-server.sh /start-server.sh
RUN chmod +x /start-server.sh
ADD https://api.papermc.io/v2/projects/velocity/versions/${VERSION}/builds/${BUILD}/downloads/velocity-${VERSION}-${BUILD}.jar /jar/server.jar


ENV EULA=TRUE
WORKDIR /minecraft
ENTRYPOINT ["/start-server.sh"]