name: Build Velocity Server

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Velocity version to build'
        default: '3.2.0-SNAPSHOT'
        type: string
      build:
        description: 'Velocity build number'
        default: '252'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile-velocity
        push: true
        tags: rudxde/minecraft-velocity:${{ inputs.version }}-${{ inputs.build }}
        platforms: linux/arm64
        build-args: |
          VERSION=${{ inputs.version }}
          BUILD=${{ inputs.build }}